
[functions.sora-video-generation]
enabled = true
verify_jwt = true
import_map = "./functions/sora-video-generation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sora-video-generation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sora-video-generation/*.html" ]

[functions.heygen-video-generation]
enabled = true
verify_jwt = true
import_map = "./functions/heygen-video-generation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/heygen-video-generation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/heygen-video-generation/*.html" ]

[functions.veo-video-generation]
enabled = true
verify_jwt = true
import_map = "./functions/veo-video-generation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/veo-video-generation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/veo-video-generation/*.html" ]

[functions.assembly-transcript-generation]
enabled = true
verify_jwt = true
import_map = "./functions/assembly-transcript-generation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/assembly-transcript-generation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/assembly-transcript-generation/*.html" ]

[functions.openai-transcript-generation]
enabled = true
verify_jwt = true
import_map = "./functions/openai-transcript-generation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/openai-transcript-generation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/openai-transcript-generation/*.html" ]

[functions.kling-api-generation]
enabled = true
verify_jwt = true
import_map = "./functions/kling-api-generation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/kling-api-generation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/kling-api-generation/*.html" ]
